# .github/release.yml


release:
  name: Release ${{ github.event.release.tag_name }}
  tag_name: ${{ github.event.release.tag_name }}
  body: |
    ## Release Date: ${{ github.event.release.published_at }}
    
    ## What's Changed
    ${{ github.event.release.body }}

    ## Contributors
    ${{ github.event.release.contributors }}

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Exciting New Features 🎉
      labels:
        - new feature
    - title: BugFix
      labels:
        - tech debt
        - bugfix
    - title: Other Changes
      labels:
        - "*"
