# .github/release.yml


release:
  name: Release ${{ github.event.release.tag_name }}
  tag_name: ${{ github.event.release.tag_name }}
  body: |
    ## Release Date: ${{ github.event.release.created_at }}
    ## What's Changed
    ${{ github.event.release.body }}

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
     
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: Other Changes
      labels:
        - "*"
